# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_form',
            name='cc_myself',
            field=models.BooleanField(default=True),
        ),
    ]
